import '../../models/Food.dart';
import '../../models/Ingredients.dart';

List<String> CrearListaBanderas() {
  return ["assets/Icons/Spain.svg", "assets/Icons/England.svg"];
}

List<String> CrearListaPaises() {
  return ["Español", "English"];
}

List<Food> createListFood() {
  List<Food> listaDeComida = [
    // Hamburguesa
    Food(
        nombre: 'BurguerMax',
        foto:
            'https://firebasestorage.googleapis.com/v0/b/tfgalejandro-fda96.appspot.com/o/hamburguesa.webp?alt=media&token=0d4cb107-8861-4cab-b342-8668e54109aa',
        isCarne: false,
        isBurguer: true,
        isEnsalada: false,
        isPostre: false,
        isPescado: false,
        isBebida: false,
        precio: 8.00,
        tiempoMinuto: 10,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: true,
        haveHuevo: true,
        haveLeche: true,
        haveMostaza: true,
        havePescado: false,
        ingredients: [
          Ingredients.SALSA_TARTARA,
          Ingredients.CARNE,
          Ingredients.LECHUGA,
          Ingredients.PAN,
        ],
        listReview: []),
    Food(
        nombre: 'BurguerUltra',
        foto:
            'https://firebasestorage.googleapis.com/v0/b/tfgalejandro-fda96.appspot.com/o/imagen.webp?alt=media&token=e3600b3c-5048-4607-8070-3b08d31d3f2e',
        isCarne: false,
        isBurguer: true,
        isEnsalada: false,
        isPostre: false,
        isPescado: false,
        isBebida: false,
        precio: 8.00,
        tiempoMinuto: 12,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: true,
        haveHuevo: true,
        haveLeche: true,
        haveMostaza: false,
        havePescado: false,
        ingredients: [
          Ingredients.KETCHUP,
          Ingredients.CARNE,
          Ingredients.LECHUGA,
          Ingredients.QUESO,
          Ingredients.TOMATE,
          Ingredients.PAN,
        ],
        listReview: []),
    Food(
        nombre: 'Burguer Buey',
        foto:
            'https://firebasestorage.googleapis.com/v0/b/tfgalejandro-fda96.appspot.com/o/haburguesaEspecial.webp?alt=media&token=db237b38-dfbb-4b23-a863-480aa6522d5b',
        isCarne: false,
        isBurguer: true,
        isEnsalada: false,
        isPostre: false,
        isPescado: false,
        isBebida: false,
        precio: 12.00,
        tiempoMinuto: 15,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: true,
        haveCacahuetes: false,
        haveGluten: true,
        haveHuevo: true,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredients: [
          Ingredients.CARNE_BUEY,
          Ingredients.QUESO,
          Ingredients.LECHUGA,
          Ingredients.PAN,
          Ingredients.TOMATE
        ],
        listReview: []),
    Food(
        nombre: 'Burguer Complete',
        foto:
            "https://firebasestorage.googleapis.com/v0/b/tfgalejandro-fda96.appspot.com/o/hamburguesaCompleta.webp?alt=media&token=e3248a95-d9be-495f-b49b-45393cfa3d69",
        isCarne: false,
        isBurguer: true,
        isEnsalada: false,
        isPostre: false,
        isPescado: false,
        isBebida: false,
        precio: 10.00,
        tiempoMinuto: 15,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: true,
        haveHuevo: true,
        haveLeche: true,
        haveMostaza: false,
        havePescado: false,
        ingredients: [
          Ingredients.CARNE,
          Ingredients.BEICON,
          Ingredients.CEBOLLA,
          Ingredients.QUESO,
          Ingredients.LECHUGA,
          Ingredients.BEICON,
          Ingredients.MAYONESA,
          Ingredients.TOMATE
        ],
        listReview: []),
    Food(
        nombre: 'The Ultimate Beef Burger',
        foto:
            'https://firebasestorage.googleapis.com/v0/b/tfgalejandro-fda96.appspot.com/o/hamburguesaBueyBeiconPatatasFritas.webp?alt=media&token=b5196fb3-51b3-4947-abaa-0de1cb638a86',
        isCarne: false,
        isBurguer: true,
        isEnsalada: false,
        isPostre: false,
        isPescado: false,
        isBebida: false,
        precio: 15.00,
        tiempoMinuto: 20,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: true,
        haveHuevo: true,
        haveLeche: true,
        haveMostaza: false,
        havePescado: false,
        ingredients: [
          Ingredients.CARNE,
          Ingredients.QUESO,
          Ingredients.BEICON,
          Ingredients.PATATAS_FRITAS,
          Ingredients.PAN,
        ],
        listReview: []),
    Food(
        nombre: 'Harmony Burger',
        foto:
            'https://firebasestorage.googleapis.com/v0/b/tfgalejandro-fda96.appspot.com/o/hamburguesaPatatasFritas.webp?alt=media&token=65e2faf0-15de-4572-8f72-1612cf6dd5fd',
        isCarne: false,
        isBurguer: true,
        isEnsalada: false,
        isPostre: false,
        isPescado: false,
        isBebida: false,
        precio: 8.20,
        tiempoMinuto: 15,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredients: [
          Ingredients.CARNE,
          Ingredients.QUESO,
          Ingredients.MAYONESA,
          Ingredients.TOMATE,
          Ingredients.LECHUGA,
          Ingredients.BEICON,
          Ingredients.PATATAS_FRITAS,
          Ingredients.PAN,
        ],
        listReview: []),
    Food(
        nombre: 'Veggie Delight',
        foto:
            'https://firebasestorage.googleapis.com/v0/b/tfgalejandro-fda96.appspot.com/o/hamburguesaVegana.jpg?alt=media&token=d0c960d4-d9c2-408f-a244-c3c1f53ae432',
        isCarne: false,
        isBurguer: true,
        isEnsalada: false,
        isPostre: false,
        isPescado: false,
        isBebida: false,
        precio: 10.50,
        tiempoMinuto: 10,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredients: [
          Ingredients.CARNE_VEGANA,
          Ingredients.KETCHUP,
          Ingredients.TOMATE,
          Ingredients.LECHUGA,
          Ingredients.CEBOLLA,
          Ingredients.PAN,
        ],
        listReview: []),
    // Ensalada
    Food(
        nombre: 'Breaded pepper',
        foto:
            'https://firebasestorage.googleapis.com/v0/b/tfgalejandro-fda96.appspot.com/o/piminetoRebo.webp?alt=media&token=9b35b041-a1d0-4c30-b0b0-3bf8260766c3',
        isCarne: false,
        isBurguer: false,
        isEnsalada: true,
        isPostre: false,
        isPescado: false,
        isBebida: false,
        precio: 8.00,
        tiempoMinuto: 17,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredients: [
          Ingredients.PIMIENTO,
          Ingredients.QUESO,
          Ingredients.BERENJENA
        ],
        listReview: []),
    Food(
        nombre: 'Shrimp Scampi',
        foto:
            'https://firebasestorage.googleapis.com/v0/b/tfgalejandro-fda96.appspot.com/o/gambasAl.webp?alt=media&token=21abe417-9266-4a2a-95fd-5048561814ad',
        isCarne: false,
        isBurguer: false,
        isEnsalada: true,
        isPostre: false,
        isPescado: false,
        isBebida: false,
        precio: 11.00,
        tiempoMinuto: 13,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredients: [
          Ingredients.GAMBA,
          Ingredients.BERENJENA,
          Ingredients.ZANAHORIA,
        ],
        listReview: []),
    Food(
        nombre: 'Vegetable cream',
        foto:
            'https://firebasestorage.googleapis.com/v0/b/tfgalejandro-fda96.appspot.com/o/cremaVerdura.webp?alt=media&token=9d2db133-eb84-432e-8cb2-460619c82f2a',
        isCarne: false,
        isBurguer: false,
        isEnsalada: true,
        isPostre: false,
        isPescado: false,
        isBebida: false,
        precio: 7.50,
        tiempoMinuto: 25,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredients: [
          Ingredients.ZANAHORIA,
          Ingredients.PATATA,
          Ingredients.PIMIENTO,
        ],
        listReview: []),
    Food(
        nombre: 'Vegetable taco',
        foto:
            "https://firebasestorage.googleapis.com/v0/b/tfgalejandro-fda96.appspot.com/o/tacoVerdura.webp?alt=media&token=4bf00c33-d928-4209-ace5-869168eac77c",
        isCarne: false,
        isBurguer: false,
        isEnsalada: true,
        isPostre: false,
        isPescado: false,
        isBebida: false,
        precio: 3.50,
        tiempoMinuto: 21,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredients: [
          Ingredients.AGUACATE,
          Ingredients.TOMATE,
          Ingredients.CEBOLLA,
          Ingredients.PIMIENTO,
          Ingredients.CHAMPINONES,
          Ingredients.ZANAHORIA,
        ],
        listReview: []),
    // Carne
    Food(
        nombre: 'Schnitzel',
        foto:
            "https://firebasestorage.googleapis.com/v0/b/tfgalejandro-fda96.appspot.com/o/schnitzel.webp?alt=media&token=386a9aae-b74d-4917-bf26-657c28900727",
        isCarne: true,
        isBurguer: false,
        isEnsalada: false,
        isPostre: false,
        isPescado: false,
        isBebida: false,
        precio: 14.00,
        tiempoMinuto: 25,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredients: [
          Ingredients.TOMATE,
          Ingredients.LIMON,
          Ingredients.AGUACATE,
          Ingredients.CARNE,
          Ingredients.HUEVO,
        ],
        listReview: []),
    Food(
        nombre: 'Iberic secret',
        foto:
            'https://firebasestorage.googleapis.com/v0/b/tfgalejandro-fda96.appspot.com/o/secretoIberico.webp?alt=media&token=9cc2b663-8e16-4119-ad51-cf8174f7c33f',
        isCarne: true,
        isBurguer: false,
        isEnsalada: false,
        isPostre: false,
        isPescado: false,
        isBebida: false,
        precio: 21.99,
        tiempoMinuto: 10,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredients: [
          Ingredients.SECRETO_IBERICO,
          Ingredients.LIMON,
          Ingredients.HUEVO,
        ],
        listReview: []),
    Food(
        nombre: 'Ragout',
        foto:
            'https://firebasestorage.googleapis.com/v0/b/tfgalejandro-fda96.appspot.com/o/ragout.webp?alt=media&token=f8baf812-58ae-4ceb-88d9-7555b4379783',
        isCarne: true,
        isBurguer: false,
        isEnsalada: false,
        isPostre: false,
        isPescado: false,
        isBebida: false,
        precio: 20.00,
        tiempoMinuto: 60,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredients: [
          Ingredients.CARNE,
          Ingredients.LECHUGA,
          Ingredients.HUEVO,
          Ingredients.GUISANTE
        ],
        listReview: []),
    Food(
        nombre: 'Meat balls',
        foto:
            'https://firebasestorage.googleapis.com/v0/b/tfgalejandro-fda96.appspot.com/o/albondiga.webp?alt=media&token=c084091e-b0fb-4919-8872-75dc72e93752',
        isCarne: true,
        isBurguer: false,
        isEnsalada: false,
        isPostre: false,
        isPescado: false,
        isBebida: false,
        precio: 8.00,
        tiempoMinuto: 25,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredients: [
          Ingredients.CARNE,
          Ingredients.LECHUGA,
          Ingredients.CEBOLLA,
          Ingredients.TOMATE
        ],
        listReview: []),
    Food(
        nombre: 'Fillet',
        foto:
            'https://firebasestorage.googleapis.com/v0/b/tfgalejandro-fda96.appspot.com/o/filete.webp?alt=media&token=0e0dfb14-043d-43bd-b075-7f2e27bd984a',
        isCarne: true,
        isBurguer: false,
        isEnsalada: false,
        isPostre: false,
        isPescado: false,
        isBebida: false,
        precio: 15.00,
        tiempoMinuto: 8,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredients: [
          Ingredients.CARNE,
          Ingredients.LIMON,
          Ingredients.CEBOLLA,
        ],
        listReview: []),
    // Pescado
    Food(
        nombre: 'Fried shrimp',
        foto:
            'https://firebasestorage.googleapis.com/v0/b/tfgalejandro-fda96.appspot.com/o/camaronesFritos.webp?alt=media&token=3cb036e1-04cb-486c-aa31-61ee877723f6',
        isCarne: false,
        isBurguer: false,
        isEnsalada: false,
        isPostre: false,
        isPescado: true,
        isBebida: false,
        precio: 12.23,
        tiempoMinuto: 5,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredients: [],
        listReview: []),
    Food(
        nombre: 'Tilapia',
        foto:
            'https://firebasestorage.googleapis.com/v0/b/tfgalejandro-fda96.appspot.com/o/tilapia.webp?alt=media&token=c0ed07de-f092-4961-a763-c0cccf68366d',
        isCarne: false,
        isBurguer: false,
        isEnsalada: false,
        isPostre: false,
        isPescado: true,
        isBebida: false,
        precio: 13.55,
        tiempoMinuto: 10,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredients: [],
        listReview: []),
    Food(
        nombre: 'Octo-Bite',
        foto:
            'https://firebasestorage.googleapis.com/v0/b/tfgalejandro-fda96.appspot.com/o/pulpoGallega.webp?alt=media&token=e6f47be7-5e77-409a-aa1e-c4c58f5e4c39',
        isCarne: false,
        isBurguer: false,
        isEnsalada: false,
        isPostre: false,
        isPescado: true,
        isBebida: false,
        precio: 10.00,
        tiempoMinuto: 60,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredients: [],
        listReview: []),
    Food(
        nombre: 'Besugo',
        foto:
            'https://firebasestorage.googleapis.com/v0/b/tfgalejandro-fda96.appspot.com/o/besugo.webp?alt=media&token=ac8a83ef-fbfe-4f0e-8532-c730d5674744',
        isCarne: false,
        isBurguer: false,
        isEnsalada: false,
        isPostre: false,
        isPescado: true,
        isBebida: false,
        precio: 19.00,
        tiempoMinuto: 20,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredients: [],
        listReview: []),
    Food(
        nombre: 'Octo-Grilled',
        foto:
            'https://firebasestorage.googleapis.com/v0/b/tfgalejandro-fda96.appspot.com/o/pulpoBrasa.webp?alt=media&token=5321a065-578c-4b22-92f7-0f29d882b2f5',
        isCarne: false,
        isBurguer: false,
        isEnsalada: false,
        isPostre: false,
        isPescado: true,
        isBebida: false,
        precio: 17.22,
        tiempoMinuto: 30,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredients: [],
        listReview: []),
    Food(
        nombre: 'Octo-chips',
        foto:
            'https://firebasestorage.googleapis.com/v0/b/tfgalejandro-fda96.appspot.com/o/pescadoPatatasFritas.webp?alt=media&token=af99a925-8334-4373-967d-b9aa859f7241',
        isCarne: false,
        isBurguer: false,
        isEnsalada: false,
        isPostre: false,
        isPescado: true,
        isBebida: false,
        precio: 15.99,
        tiempoMinuto: 10,
        haveApio: true,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: true,
        haveCacahuetes: false,
        haveGluten: true,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredients: [],
        listReview: []),
    // Bebida
    Food(
        nombre: 'Coca cola',
        foto:
            'https://firebasestorage.googleapis.com/v0/b/tfgalejandro-fda96.appspot.com/o/cocaCola.webp?alt=media&token=d500a378-4be8-41fb-92bd-28254d516ae9',
        isCarne: false,
        isBurguer: false,
        isEnsalada: false,
        isPostre: false,
        isPescado: false,
        isBebida: true,
        precio: 2.0,
        tiempoMinuto: 0,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredients: [],
        listReview: []),
    Food(
        nombre: 'Coca cola zero',
        foto:
            'https://firebasestorage.googleapis.com/v0/b/tfgalejandro-fda96.appspot.com/o/cocaColaZero.webp?alt=media&token=40f7e86c-6512-4fbb-bc7e-15b136858e86',
        isCarne: false,
        isBurguer: false,
        isEnsalada: false,
        isPostre: false,
        isPescado: false,
        isBebida: true,
        precio: 2.0,
        tiempoMinuto: 0,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredients: [],
        listReview: []),
    Food(
        nombre: 'Fanta (Orange)',
        foto:
            'https://firebasestorage.googleapis.com/v0/b/tfgalejandro-fda96.appspot.com/o/fantaNaranja.webp?alt=media&token=289b1862-c9fc-4cf1-bf51-b52159397644',
        isCarne: false,
        isBurguer: false,
        isEnsalada: false,
        isPostre: false,
        isPescado: false,
        isBebida: true,
        precio: 2.0,
        tiempoMinuto: 0,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredients: [],
        listReview: []),
    Food(
        nombre: 'Fanta (Lemon)',
        foto:
            'https://firebasestorage.googleapis.com/v0/b/tfgalejandro-fda96.appspot.com/o/fantaLimon.webp?alt=media&token=f669c7b6-e575-47f1-b91e-a479c9f67756',
        isCarne: false,
        isBurguer: false,
        isEnsalada: false,
        isPostre: false,
        isPescado: false,
        isBebida: true,
        precio: 2.0,
        tiempoMinuto: 0,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredients: [],
        listReview: []),
    Food(
        nombre: 'Te',
        foto:
            'https://firebasestorage.googleapis.com/v0/b/tfgalejandro-fda96.appspot.com/o/te.webp?alt=media&token=2db55cd2-f38c-4566-9dce-83044f2fe71d',
        isCarne: false,
        isBurguer: false,
        isEnsalada: false,
        isPostre: false,
        isPescado: false,
        isBebida: true,
        precio: 1.50,
        tiempoMinuto: 0,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredients: [],
        listReview: []),
    // Postre
    Food(
        nombre: 'Pistachio cake',
        foto:
            'https://firebasestorage.googleapis.com/v0/b/tfgalejandro-fda96.appspot.com/o/pistacho.webp?alt=media&token=14450d94-f9ab-42a3-a40f-d55a1db57ddd',
        isCarne: false,
        isBurguer: false,
        isEnsalada: false,
        isPostre: true,
        isPescado: false,
        isBebida: false,
        precio: 7.22,
        tiempoMinuto: 60,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredients: [],
        listReview: []),
    Food(
        nombre: 'Cupcake',
        foto:
            'https://firebasestorage.googleapis.com/v0/b/tfgalejandro-fda96.appspot.com/o/cupcakes.webp?alt=media&token=ebdbb63b-2fc8-4d88-a5bc-faca35632ab7',
        isCarne: false,
        isBurguer: false,
        isEnsalada: false,
        isPostre: true,
        isPescado: false,
        isBebida: false,
        precio: 1.70,
        tiempoMinuto: 15,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredients: [],
        listReview: []),
    Food(
        nombre: 'Tiramisu',
        foto:
            'https://firebasestorage.googleapis.com/v0/b/tfgalejandro-fda96.appspot.com/o/Tiramisu.webp?alt=media&token=3777f10c-bf06-4ebd-bb2b-0ae1e61bf930',
        isCarne: false,
        isBurguer: false,
        isEnsalada: false,
        isPostre: true,
        isPescado: false,
        isBebida: false,
        precio: 4.00,
        tiempoMinuto: 30,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredients: [],
        listReview: []),
    Food(
        nombre: 'Raspberry Tart',
        foto:
            'https://firebasestorage.googleapis.com/v0/b/tfgalejandro-fda96.appspot.com/o/TartaFrambuesa.webp?alt=media&token=ca1a8030-fc28-4212-abf3-3e3a3b9468a3',
        isCarne: false,
        isBurguer: false,
        isEnsalada: false,
        isPostre: true,
        isPescado: false,
        isBebida: false,
        precio: 6.00,
        tiempoMinuto: 60,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredients: [],
        listReview: []),
  ];
  return listaDeComida;
}
