import 'dart:convert';

import '../../model/Comida.dart';
import '../../model/Ingrediente.dart';

Future<List<dynamic>> leerListaJson(String json) async {
  final listaMap = jsonDecode(json);
  return listaMap;
}

List<String> CrearListaBanderas() {
  return ["assets/Icons/Spain.svg", "assets/Icons/England.svg"];
}

List<String> CrearListaPaises() {
  return ["Español", "English"];
}

double conversorMoneda(double original) {
  return 2.2;
}

List<Comida> CrearListaDeComida() {
  List<Comida> listaDeComida = [
    // Hamburguesa
    const Comida(
        nombre: 'BurguerMax',
        foto: 'assets/images/hamburguesa.webp',
        isCarne: false,
        isBurguer: true,
        isEnsalada: false,
        isPostre: false,
        isPescado: false,
        isBebida: false,
        precio: 5.12,
        tiempoMinuto: 20,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: true,
        haveHuevo: true,
        haveLeche: true,
        haveMostaza: true,
        havePescado: false,
        ingredientes: [
          Ingrediente.SALSA_TARTARA,
          Ingrediente.CARNE,
          Ingrediente.LECHUGA,
          Ingrediente.PAN,
        ]),
    const Comida(
        nombre: 'BurguerUltra',
        foto: 'assets/images/imagen.webp',
        isCarne: false,
        isBurguer: true,
        isEnsalada: false,
        isPostre: false,
        isPescado: false,
        isBebida: false,
        precio: 4.12,
        tiempoMinuto: 20,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: true,
        haveHuevo: true,
        haveLeche: true,
        haveMostaza: false,
        havePescado: false,
        ingredientes: [
          Ingrediente.KETCHUP,
          Ingrediente.CARNE,
          Ingrediente.LECHUGA,
          Ingrediente.QUESO,
          Ingrediente.TOMATE,
          Ingrediente.PAN,
        ]),
    const Comida(
        nombre: 'Burguer Buey',
        foto: 'assets/images/haburguesaEspecial.webp',
        isCarne: false,
        isBurguer: true,
        isEnsalada: false,
        isPostre: false,
        isPescado: false,
        isBebida: false,
        precio: 4.50,
        tiempoMinuto: 20,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: true,
        haveCacahuetes: false,
        haveGluten: true,
        haveHuevo: true,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredientes: [
          Ingrediente.CARNE_BUEY,
          Ingrediente.QUESO,
          Ingrediente.LECHUGA,
          Ingrediente.PAN,
          Ingrediente.TOMATE
        ]),
    const Comida(
        nombre: 'Burguer Complete',
        foto: 'assets/images/hamburguesaCompleta.webp',
        isCarne: false,
        isBurguer: true,
        isEnsalada: false,
        isPostre: false,
        isPescado: false,
        isBebida: false,
        precio: 4.50,
        tiempoMinuto: 20,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: true,
        haveHuevo: true,
        haveLeche: true,
        haveMostaza: false,
        havePescado: false,
        ingredientes: [
          Ingrediente.CARNE,
          Ingrediente.BEICON,
          Ingrediente.CEBOLLA,
          Ingrediente.QUESO,
          Ingrediente.LECHUGA,
          Ingrediente.BEICON,
          Ingrediente.MAYONESA,
          Ingrediente.TOMATE
        ]),
    const Comida(
        nombre: 'The Ultimate Beef Burger',
        foto: 'assets/images/hamburguesaBueyBeiconPatatasFritas.webp',
        isCarne: false,
        isBurguer: true,
        isEnsalada: false,
        isPostre: false,
        isPescado: false,
        isBebida: false,
        precio: 4.50,
        tiempoMinuto: 20,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: true,
        haveHuevo: true,
        haveLeche: true,
        haveMostaza: false,
        havePescado: false,
        ingredientes: [
          Ingrediente.CARNE,
          Ingrediente.QUESO,
          Ingrediente.BEICON,
          Ingrediente.PATATAS_FRITAS,
          Ingrediente.PAN,
        ]),
    const Comida(
        nombre: 'Harmony Burger',
        foto: 'assets/images/hamburguesaPatatasFritas.webp',
        isCarne: false,
        isBurguer: true,
        isEnsalada: false,
        isPostre: false,
        isPescado: false,
        isBebida: false,
        precio: 4.50,
        tiempoMinuto: 20,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredientes: [
          Ingrediente.CARNE,
          Ingrediente.QUESO,
          Ingrediente.MAYONESA,
          Ingrediente.TOMATE,
          Ingrediente.LECHUGA,
          Ingrediente.BEICON,
          Ingrediente.PATATAS_FRITAS,
          Ingrediente.PAN,
        ]),
    const Comida(
        nombre: 'Veggie Delight',
        foto: 'assets/images/hamburguesaVegana.jpg',
        isCarne: false,
        isBurguer: true,
        isEnsalada: false,
        isPostre: false,
        isPescado: false,
        isBebida: false,
        precio: 4.50,
        tiempoMinuto: 20,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredientes: [
          Ingrediente.CARNE_VEGANA,
          Ingrediente.KETCHUP,
          Ingrediente.TOMATE,
          Ingrediente.LECHUGA,
          Ingrediente.CEBOLLA,
          Ingrediente.PAN,
        ]),
    // Ensalada
    const Comida(
        nombre: 'Breaded pepper',
        foto: 'assets/images/piminetoRebo.webp',
        isCarne: false,
        isBurguer: false,
        isEnsalada: true,
        isPostre: false,
        isPescado: false,
        isBebida: false,
        precio: 5.99,
        tiempoMinuto: 20,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredientes: [
          Ingrediente.PIMIENTO,
          Ingrediente.QUESO,
          Ingrediente.BERENJENA
        ]),
    const Comida(
        nombre: 'Shrimp Scampi',
        foto: 'assets/images/gambasAl.webp',
        isCarne: false,
        isBurguer: false,
        isEnsalada: true,
        isPostre: false,
        isPescado: false,
        isBebida: false,
        precio: 3.22,
        tiempoMinuto: 20,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredientes: [
          Ingrediente.GAMBA,
          Ingrediente.BERENJENA,
          Ingrediente.ZANAHORIA,
        ]),
    const Comida(
        nombre: 'Vegetable cream',
        foto: 'assets/images/cremaVerdura.webp',
        isCarne: false,
        isBurguer: false,
        isEnsalada: true,
        isPostre: false,
        isPescado: false,
        isBebida: false,
        precio: 3.22,
        tiempoMinuto: 20,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredientes: [
          Ingrediente.ZANAHORIA,
          Ingrediente.PATATA,
          Ingrediente.PIMIENTO,
        ]),
    const Comida(
        nombre: 'Vegetable taco',
        foto: 'assets/images/tacoVerdura.webp',
        isCarne: false,
        isBurguer: false,
        isEnsalada: true,
        isPostre: false,
        isPescado: false,
        isBebida: false,
        precio: 3.22,
        tiempoMinuto: 20,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredientes: [
          Ingrediente.AGUACATE,
          Ingrediente.TOMATE,
          Ingrediente.CEBOLLA,
          Ingrediente.PIMIENTO,
          Ingrediente.CHAMPINONES,
          Ingrediente.ZANAHORIA,
        ]),
    // Carne
    const Comida(
        nombre: 'Scnizel',
        foto: 'assets/images/schnitzel.webp',
        isCarne: true,
        isBurguer: false,
        isEnsalada: false,
        isPostre: false,
        isPescado: false,
        isBebida: false,
        precio: 3.22,
        tiempoMinuto: 20,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredientes: [
          Ingrediente.TOMATE,
          Ingrediente.LIMON,
          Ingrediente.AGUACATE,
          Ingrediente.CARNE,
          Ingrediente.HUEVO,
        ]),
    const Comida(
        nombre: 'Iberic secret',
        foto: 'assets/images/secretoIberico.webp',
        isCarne: true,
        isBurguer: false,
        isEnsalada: false,
        isPostre: false,
        isPescado: false,
        isBebida: false,
        precio: 3.22,
        tiempoMinuto: 20,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredientes: [
          Ingrediente.SECRETO_IBERICO,
          Ingrediente.LIMON,
          Ingrediente.HUEVO,
        ]),
    const Comida(
        nombre: 'Ragout',
        foto: 'assets/images/ragout.webp',
        isCarne: true,
        isBurguer: false,
        isEnsalada: false,
        isPostre: false,
        isPescado: false,
        isBebida: false,
        precio: 3.22,
        tiempoMinuto: 20,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredientes: [
          Ingrediente.CARNE,
          Ingrediente.LECHUGA,
          Ingrediente.HUEVO,
          Ingrediente.GUISANTE
        ]),
    const Comida(
        nombre: 'Meat balls',
        foto: 'assets/images/albondiga.webp',
        isCarne: true,
        isBurguer: false,
        isEnsalada: false,
        isPostre: false,
        isPescado: false,
        isBebida: false,
        precio: 3.22,
        tiempoMinuto: 20,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredientes: [
          Ingrediente.CARNE,
          Ingrediente.LECHUGA,
          Ingrediente.CEBOLLA,
          Ingrediente.TOMATE
        ]),
    const Comida(
        nombre: 'Fillet',
        foto: 'assets/images/filete.webp',
        isCarne: true,
        isBurguer: false,
        isEnsalada: false,
        isPostre: false,
        isPescado: false,
        isBebida: false,
        precio: 3.22,
        tiempoMinuto: 20,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredientes: [
          Ingrediente.CARNE,
          Ingrediente.LIMON,
          Ingrediente.CEBOLLA,
        ]),
    // Pescado
    const Comida(
        nombre: 'Fried shrimp',
        foto: 'assets/images/camaronesFritos.webp',
        isCarne: false,
        isBurguer: false,
        isEnsalada: false,
        isPostre: false,
        isPescado: true,
        isBebida: false,
        precio: 3.22,
        tiempoMinuto: 20,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredientes: []),
    const Comida(
        nombre: 'Tilapia',
        foto: 'assets/images/tilapia.webp',
        isCarne: false,
        isBurguer: false,
        isEnsalada: false,
        isPostre: false,
        isPescado: true,
        isBebida: false,
        precio: 3.22,
        tiempoMinuto: 20,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredientes: []),
    const Comida(
        nombre: 'Octo-Bite',
        foto: 'assets/images/pulpoGallega.webp',
        isCarne: false,
        isBurguer: false,
        isEnsalada: false,
        isPostre: false,
        isPescado: true,
        isBebida: false,
        precio: 3.22,
        tiempoMinuto: 20,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredientes: []),
    const Comida(
        nombre: 'Besugo',
        foto: 'assets/images/besugo.webp',
        isCarne: false,
        isBurguer: false,
        isEnsalada: false,
        isPostre: false,
        isPescado: true,
        isBebida: false,
        precio: 3.22,
        tiempoMinuto: 20,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredientes: []),
    const Comida(
        nombre: 'Octo-Grilled',
        foto: 'assets/images/pulpoBrasa.webp',
        isCarne: false,
        isBurguer: false,
        isEnsalada: false,
        isPostre: false,
        isPescado: true,
        isBebida: false,
        precio: 3.22,
        tiempoMinuto: 20,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredientes: []),
    const Comida(
        nombre: 'Octo-chips',
        foto: 'assets/images/pescadoPatatasFritas.webp',
        isCarne: false,
        isBurguer: false,
        isEnsalada: false,
        isPostre: false,
        isPescado: true,
        isBebida: false,
        precio: 3.22,
        tiempoMinuto: 20,
        haveApio: true,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: true,
        haveCacahuetes: false,
        haveGluten: true,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredientes: []),
    // Bebida
    const Comida(
        nombre: 'Coca cola',
        foto: 'assets/images/cocaCola.webp',
        isCarne: false,
        isBurguer: false,
        isEnsalada: false,
        isPostre: false,
        isPescado: false,
        isBebida: true,
        precio: 3.22,
        tiempoMinuto: 20,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredientes: []),
    const Comida(
        nombre: 'Coca cola zero',
        foto: 'assets/images/cocaColaZero.webp',
        isCarne: false,
        isBurguer: false,
        isEnsalada: false,
        isPostre: false,
        isPescado: false,
        isBebida: true,
        precio: 3.22,
        tiempoMinuto: 20,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredientes: []),
    const Comida(
        nombre: 'Fanta (Orange)',
        foto: 'assets/images/fantaNaranja.webp',
        isCarne: false,
        isBurguer: false,
        isEnsalada: false,
        isPostre: false,
        isPescado: false,
        isBebida: true,
        precio: 3.22,
        tiempoMinuto: 20,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredientes: []),
    const Comida(
        nombre: 'Fanta (Lemon)',
        foto: 'assets/images/fantaLimon.webp',
        isCarne: false,
        isBurguer: false,
        isEnsalada: false,
        isPostre: false,
        isPescado: false,
        isBebida: true,
        precio: 3.22,
        tiempoMinuto: 20,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredientes: []),
    const Comida(
        nombre: 'Te',
        foto: 'assets/images/te.webp',
        isCarne: false,
        isBurguer: false,
        isEnsalada: false,
        isPostre: false,
        isPescado: false,
        isBebida: true,
        precio: 1.22,
        tiempoMinuto: 2,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredientes: []),
    // Postre
    const Comida(
        nombre: 'Pistachio cake',
        foto: 'assets/images/pistacho.webp',
        isCarne: false,
        isBurguer: false,
        isEnsalada: false,
        isPostre: true,
        isPescado: false,
        isBebida: false,
        precio: 3.22,
        tiempoMinuto: 20,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredientes: []),
    const Comida(
        nombre: 'Cupcake',
        foto: 'assets/images/cupcakes.webp',
        isCarne: false,
        isBurguer: false,
        isEnsalada: false,
        isPostre: true,
        isPescado: false,
        isBebida: false,
        precio: 1.00,
        tiempoMinuto: 2,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredientes: []),
    const Comida(
        nombre: 'Tiramisu',
        foto: 'assets/images/Tiramisu.webp',
        isCarne: false,
        isBurguer: false,
        isEnsalada: false,
        isPostre: true,
        isPescado: false,
        isBebida: false,
        precio: 1.00,
        tiempoMinuto: 2,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredientes: []),
    const Comida(
        nombre: 'Raspberry Tart',
        foto: 'assets/images/TartaFrambuesa.webp',
        isCarne: false,
        isBurguer: false,
        isEnsalada: false,
        isPostre: true,
        isPescado: false,
        isBebida: false,
        precio: 1.00,
        tiempoMinuto: 2,
        haveApio: false,
        haveCrustaceos: false,
        haveMoluscos: false,
        haveAzufre: false,
        haveCacahuetes: false,
        haveGluten: false,
        haveHuevo: false,
        haveLeche: false,
        haveMostaza: false,
        havePescado: false,
        ingredientes: []),
  ];
  return listaDeComida;
}
